# Generated by Django 2.2.1 on 2019-05-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=120)),
                ('subject_desc', models.TextField()),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_desc', models.TextField()),
                ('question_answer', models.TextField()),
                ('question_point', models.IntegerField()),
                ('question_time', models.TimeField()),
                ('question_date', models.DateTimeField()),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Subject')),
            ],
        ),
    ]
