# Generated by Django 2.2.1 on 2019-05-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20190515_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='soru',
            new_name='konu',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_desc',
            new_name='question_description',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_desc',
            new_name='subject_description',
        ),
    ]
