# Generated by Django 2.2.1 on 2019-05-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20190515_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='lesson_description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='lesson_name',
        ),
    ]
