# Generated by Django 2.2.1 on 2019-05-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20190515_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
